name: 'Monorepo Split'

description: 'Split monorepo packages to many repositories'

inputs:
    package-directory:
        description: 'Local package directory'
        required: true
    split-repository-organization:
        description: 'Remote organization'
        required: true
    split-repository-name:
        description: 'Remove repository'
        required: true
    commit-message:
        description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
        default: 'Package split ORIGIN_COMMIT'
        required: false
    tag:
        description: '[Optional] Tag to be released'
        required: false
    user-email:
        description: '[Optional] Git User Email'
        required: false
    user-name:
        description: '[Optional] Git User Name'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.package-directory }}
        - ${{ inputs.split-repository-organization }}
        - ${{ inputs.split-repository-name }}
        - ${{ inputs.user-email }}
        - ${{ inputs.commit-message }}
        - ${{ inputs.tag }}

branding:
    icon: maximize-2
    color: purple
