name: 'Monorepo Split'

on:
    push:
        branches:
            - master

        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

jobs:
    monorepo_split:
        runs-on: ubuntu-latest

        steps:
            -
                # debug
                run: echo ${{ github.event_name }}

            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            -
                # Uses an action in the root directory
                uses: "./packages/monorepo-split-github-action"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/monorepo-split-github-action'
                    split-repository-organization: 'symplify'
                    split-repository-name: 'monorepo-split-github-action'
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
                    tag: ${{ steps.previous_tag.outputs.tag }}
